package fr.polytech.mnia;

public enum AlgorithmId {
    VALUE_ITERATION,
    POLICY_ITERATION,
    MODIFIED_POLICY_ITERATION,
    INCREMENTAL_VALUE_ITERATION,
    BACKWARD_INDUCTION,
    PRIORITIZED_VALUE_ITERATION
}